name: Podman & Integration Tests - Spring Boot

on:
  push:
    paths:
      - '**/integrationtest/**'
    branches:
      - main

  pull_request:
    paths:
      - '**/integrationtest/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          maven-version: 3.9.6

      - name: Install Podman
        run: sudo apt-get install -y podman

      - name: Build and test
        run: mvn clean install -PITs
        env:
          PODMAN_HOST: unix://${XDG_RUNTIME_DIR}/podman/podman.sock
          TESTCONTAINERS_RYUK_DISABLED: true