name: Podman & Unit Tests - Spring Boot

on:
    push:
        paths:
            - '**/integrationtest/**'
            - '**/unittest/**'
        branches:
            - 'master'
            - 'main'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v1
              with:
                  java-version: 21
                  maven-version: '3.9.6'

            - name: Install Podman
              run: sudo apt-get install -y podman  

            - name: Run unit tests
              run: mvn clean install
              env:
                PODMAN_HOST: unix://${XDG_RUNTIME_DIR}/podman/podman.sock
                TESTCONTAINERS_RYUK_DISABLED: true
